allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: false
  prisma: true
  sharp: true
  simple-git-hooks: false
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver
