import 'server-only'
import { prisma } from '@/lib/prisma'
import { random_token, hash_token } from '@/lib/mcp/tokens'

// An MCP client cannot hand a file to a tool: tool arguments are generated by
// the model, so the bytes would have to pass through its output. Instead the
// tool mints a one-time capability URL and the agent PUTs the file to it
// directly — disk to network, never through the model.
//
// The token is stored sha256-hashed, exactly like mcp_oauth_code, and is bound
// to the user and transaction at creation time so a leaked URL cannot be
// redirected at someone else's ledger.

export const UPLOAD_TOKEN_TTL_MS = 10 * 60 * 1000

export type UploadGrant = {
  id: string
  user_id: string
  transaction_id: string
  filename: string
  content_type: string
}

export async function create_upload_grant(input: {
  user_id: string
  transaction_id: string
  filename: string
  content_type: string
}): Promise<{ token: string; expires_at: Date }> {
  const token = random_token(32)
  const expires_at = new Date(Date.now() + UPLOAD_TOKEN_TTL_MS)
  await prisma.mcp_attachment_upload.create({
    data: {
      token_hash: hash_token(token),
      user_id: input.user_id,
      transaction_id: input.transaction_id,
      filename: input.filename,
      content_type: input.content_type,
      expires_at,
    },
  })
  return { token, expires_at }
}

export type ClaimResult = { ok: true; grant: UploadGrant } | { ok: false; error: string }

// Claims the grant for use: single-use and time-bound. The row is marked
// consumed before the body is read, so a retry of an in-flight upload cannot
// post the file twice.
export async function claim_upload_grant(raw_token: string): Promise<ClaimResult> {
  const row = await prisma.mcp_attachment_upload.findUnique({ where: { token_hash: hash_token(raw_token) } })
  if (!row) return { ok: false, error: 'Unknown or already used upload URL' }
  if (row.consumed_at) return { ok: false, error: 'This upload URL has already been used' }
  if (row.expires_at.getTime() <= Date.now()) return { ok: false, error: 'This upload URL has expired — request a new one' }

  // updateMany with the consumed_at guard makes the claim atomic: two
  // concurrent PUTs race here and exactly one sees count === 1.
  const claimed = await prisma.mcp_attachment_upload.updateMany({
    where: { id: row.id, consumed_at: null },
    data: { consumed_at: new Date() },
  })
  if (claimed.count !== 1) return { ok: false, error: 'This upload URL has already been used' }

  return {
    ok: true,
    grant: {
      id: row.id,
      user_id: row.user_id,
      transaction_id: row.transaction_id,
      filename: row.filename,
      content_type: row.content_type,
    },
  }
}

// A claim that never produced an attachment (bad bytes, blob failure) is
// released so the agent can retry with the same URL rather than re-minting one.
export async function release_upload_grant(id: string): Promise<void> {
  await prisma.mcp_attachment_upload.updateMany({ where: { id }, data: { consumed_at: null } })
}
