import { PrismaClient } from '@/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import 'dotenv/config'
import { env, isDev, isProd } from './env'
import { logger } from './logger'
import { currentMetrics, SLOW_QUERY_THRESHOLD_MS } from './metrics/context'

const adapter = new PrismaPg({ connectionString: env.DATABASE_URL })

// Prevent multiple instances in development
const globalForPrisma = globalThis as unknown as {
  prisma: ReturnType<typeof buildPrisma> | undefined
}

const globalForPrismaConnection = globalThis as unknown as {
  prismaConnectionLogged: boolean | undefined
}

// Tables generated by profiling itself; skip instrumentation for these or the
// persist write would recurse and double-count.
const PROFILING_MODELS = new Set(['server_metric', 'slow_query', 'web_vital'])

function buildPrisma() {
  const base = new PrismaClient({
    adapter,
    log: isDev() ? ['error', 'warn'] : ['error'],
  })

  return base.$extends({
    name: 'profiling',
    query: {
      $allOperations: async ({ model, operation, args, query }) => {
        if (model && PROFILING_MODELS.has(model)) return query(args)
        const ctx = currentMetrics()
        if (!ctx) return query(args)

        const start = performance.now()
        try {
          return await query(args)
        } finally {
          const ms = performance.now() - start
          ctx.db_query_count += 1
          ctx.db_query_ms += ms
          if (ms >= SLOW_QUERY_THRESHOLD_MS) {
            ctx.slow_queries.push({
              model: model ?? undefined,
              action: operation,
              duration_ms: ms,
            })
          }
        }
      },
    },
  })
}

export const prisma = globalForPrisma.prisma ?? buildPrisma()

if (!globalForPrismaConnection.prismaConnectionLogged) {
  globalForPrismaConnection.prismaConnectionLogged = true
  prisma
    .$connect()
    .then(() => {
      logger.info('Database connected')
    })
    .catch(error => {
      globalForPrismaConnection.prismaConnectionLogged = false
      logger.error({ err: error }, 'Database connection failed')
    })
}

if (!isProd()) globalForPrisma.prisma = prisma
